spring.application.name=vitalia-api

## SENHA DO JWT
api.security.token.secret=${JWT_SECRET}

# ORACLE DATABASE
spring.datasource.url=${ORACLE_URL}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=${ORACLE_USER}
spring.datasource.password=${ORACLE_PASSWORD}

# JPA / HIBERNATE
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# FLYWAY
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.clean-disabled=false
spring.flyway.clean-on-validation-error=true
spring.flyway.out-of-order=true

# SWAGGER
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=alpha

# SERVER
server.port=${PORT:8080}

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2