CREATE TABLE tb_vitalia_app_role (
                                     role_id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
                                     role_name VARCHAR2(50 CHAR) NOT NULL,
                                     PRIMARY KEY (role_id)
);

CREATE TABLE tb_vitalia_app_user (
                                     user_id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
                                     created_at TIMESTAMP(6) NOT NULL,
                                     email VARCHAR2(150 CHAR) NOT NULL,
                                     full_name VARCHAR2(150 CHAR) NOT NULL,
                                     password_hash VARCHAR2(255 CHAR) NOT NULL,
                                     phone VARCHAR2(30 CHAR),
                                     status VARCHAR2(20 CHAR) NOT NULL CHECK (status IN ('ACTIVE','INACTIVE','BLOCKED')),
                                     updated_at TIMESTAMP(6) NOT NULL,
                                     PRIMARY KEY (user_id)
);

CREATE TABLE tb_vitalia_app_user_role (
                                          user_id NUMBER(19,0) NOT NULL,
                                          role_id NUMBER(19,0) NOT NULL,
                                          PRIMARY KEY (user_id, role_id)
);

CREATE TABLE tb_vitalia_appointment (
                                        appointment_id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
                                        appointment_date TIMESTAMP(6) NOT NULL,
                                        notes VARCHAR2(1000 CHAR),
                                        status VARCHAR2(30 CHAR) NOT NULL,
                                        pet_id NUMBER(19,0) NOT NULL,
                                        veterinarian_id NUMBER(19,0) NOT NULL,
                                        PRIMARY KEY (appointment_id)
);

CREATE TABLE tb_vitalia_breed (
                                  breed_id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
                                  name VARCHAR2(100 CHAR) NOT NULL,
                                  species_id NUMBER(19,0) NOT NULL,
                                  PRIMARY KEY (breed_id)
);

CREATE TABLE tb_vitalia_clinical_record (
                                            clinical_record_id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
                                            diagnosis VARCHAR2(1000 CHAR),
                                            observations VARCHAR2(2000 CHAR),
                                            record_date TIMESTAMP(6) NOT NULL,
                                            treatment VARCHAR2(2000 CHAR),
                                            appointment_id NUMBER(19,0),
                                            pet_id NUMBER(19,0) NOT NULL,
                                            veterinarian_id NUMBER(19,0) NOT NULL,
                                            PRIMARY KEY (clinical_record_id)
);

CREATE TABLE tb_vitalia_health_alert (
                                         alert_id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
                                         alert_type VARCHAR2(50 CHAR) NOT NULL,
                                         created_at TIMESTAMP(6) NOT NULL,
                                         measurement_id NUMBER(19,0),
                                         message VARCHAR2(2000 CHAR) NOT NULL,
                                         resolved_at TIMESTAMP(6),
                                         severity VARCHAR2(20 CHAR) NOT NULL,
                                         status VARCHAR2(20 CHAR) NOT NULL,
                                         pet_id NUMBER(19,0) NOT NULL,
                                         PRIMARY KEY (alert_id)
);

CREATE TABLE tb_vitalia_pet (
                                pet_id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
                                birth_date DATE,
                                breed_id NUMBER(19,0),
                                created_at TIMESTAMP(6) NOT NULL,
                                name VARCHAR2(100 CHAR) NOT NULL,
                                sex VARCHAR2(20 CHAR) NOT NULL,
                                status VARCHAR2(20 CHAR) NOT NULL,
                                weight_kg NUMBER(6,2),
                                owner_user_id NUMBER(19,0) NOT NULL,
                                PRIMARY KEY (pet_id)
);

CREATE TABLE tb_vitalia_species (
                                    species_id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
                                    name VARCHAR2(80 CHAR) NOT NULL,
                                    PRIMARY KEY (species_id)
);

ALTER TABLE tb_vitalia_app_role ADD CONSTRAINT UK7vn0t4qyq4ut7v8uxphfjyyqq UNIQUE (role_name);
ALTER TABLE tb_vitalia_app_user ADD CONSTRAINT UKs4nj01r0v6luicgccyhspab3f UNIQUE (email);
ALTER TABLE tb_vitalia_species ADD CONSTRAINT UK9odko15wc1jbuq8bydmdegans UNIQUE (name);

ALTER TABLE tb_vitalia_app_user_role ADD CONSTRAINT FK6bho26i5axspktdn4fs1w3bad FOREIGN KEY (role_id) REFERENCES tb_vitalia_app_role;
ALTER TABLE tb_vitalia_app_user_role ADD CONSTRAINT FKl1owct1hogp6bs8joyjeux862 FOREIGN KEY (user_id) REFERENCES tb_vitalia_app_user;
ALTER TABLE tb_vitalia_appointment ADD CONSTRAINT FKjkuecqf6gti969swxyn15sgu8 FOREIGN KEY (pet_id) REFERENCES tb_vitalia_pet;
ALTER TABLE tb_vitalia_appointment ADD CONSTRAINT FKeelk1tea81kdomu5fm6bw1w5a FOREIGN KEY (veterinarian_id) REFERENCES tb_vitalia_app_user;
ALTER TABLE tb_vitalia_clinical_record ADD CONSTRAINT FK6cq3i2vqxpwrl10gljy89p4x5 FOREIGN KEY (appointment_id) REFERENCES tb_vitalia_appointment;
ALTER TABLE tb_vitalia_clinical_record ADD CONSTRAINT FKn3xlfsf1itcotnrmxyg9fudu7 FOREIGN KEY (pet_id) REFERENCES tb_vitalia_pet;
ALTER TABLE tb_vitalia_clinical_record ADD CONSTRAINT FK8h4y15f65phfjkpy8hd0ufff1 FOREIGN KEY (veterinarian_id) REFERENCES tb_vitalia_app_user;
ALTER TABLE tb_vitalia_health_alert ADD CONSTRAINT FKb65jc8ejxa4ii1kdl01odco4 FOREIGN KEY (pet_id) REFERENCES tb_vitalia_pet;
ALTER TABLE tb_vitalia_pet ADD CONSTRAINT FKnboavohwv8o4hgy1v7rjd8g31 FOREIGN KEY (owner_user_id) REFERENCES tb_vitalia_app_user;