MERGE INTO TB_VITALIA_APP_ROLE R USING (
    SELECT 'TUTOR' AS ROLE_NAME FROM DUAL UNION ALL
    SELECT 'VETERINARIAN' FROM DUAL UNION ALL
    SELECT 'ADMIN' FROM DUAL
) SRC
    ON (R.ROLE_NAME = SRC.ROLE_NAME)
    WHEN NOT MATCHED THEN
        INSERT (ROLE_NAME) VALUES (SRC.ROLE_NAME);